format = """\
[](fg:#9cabd1)\
[\uF303](bg:#9cabd1 fg:#090c0c)\
[](fg:#9cabd1 bg:#689ef1)\
$time\
[](fg:#689ef1 bg:#3b4866)\
$directory\
[](fg:#3b4866 bg:#242d3c)\
$conda\
[](fg:#242d3c bg:#212836)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#212836)\
"""

[directory]
format = "[ $path ]($style)"
style = "fg:#689ef1 bg:#3b4866"

[conda]
format = '[$symbol $environment]($style)'
style = "fg:#9cabd1 bg:#242d3c"
symbol = "󱔎"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#9cabd1 bg:#212836"

[git_status]
format = '[$all_status]($style)'
style = "fg:#9cabd1 bg:#212836"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#689ef1 fg:#3b4866)]($style)'
